name: gui
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
 # State Management
  flutter_bloc: ^6.1.1
  # To compare objects in Dart
  equatable: ^1.2.5

  dio: ^3.0.10

  # handles navigation and the material app 
  get: ^3.21.1

  # localization 
  intl: ^0.16.1

  # Fonts 
  google_fonts: ^1.1.1
  # resizes text to fit perfectly 

  # Mask for the text field
  mask_text_input_formatter: ^1.1.0



  # Icons
  eva_icons_flutter: ^2.0.1
  # Generates fake data
  faker: ^1.3.0


  # To launche Email Phone Website url  
  url_launcher: ^5.7.10


  flutter_screenutil: ^4.0.2+1


  # Dependency Injections
  get_it: ^5.0.1
  # shared_preferences: ^0.5.12+4
dev_dependencies:
  logger: ^0.9.4
  flutter_native_splash: ^0.3.1+1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true



flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color is the only required parameter.  It sets the background color of your splash screen.
  color: "#DDE2FF"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file.
  image: assets/logo.png

  # The color_dark and image_dark are parameters that set the color and image when the device is
  # in dark mode.  If they are not specified, the app will use the color and image above.
  # If the image_dark parameter is specified, color_dark must be specified.


  # The android and ios parameters can be used to disable generating a splash screen on a given
  # platform.
  android: true
  ios: true
  web: true

